INSERT INTO roles (name, use) VALUES ('市民', false);
INSERT INTO roles (name, use) VALUES ('市民', false);
INSERT INTO roles (name, use) VALUES ('人狼', false);
INSERT INTO roles (name, use) VALUES ('人狼', false);
INSERT INTO roles (name, use) VALUES ('占い師', false);
INSERT INTO roles (name, use) VALUES ('怪盗', false);
INSERT INTO userinfo (username, role, selected) VALUES ('user1', null, false);
INSERT INTO userinfo (username, role, selected) VALUES ('user2', null, false);
INSERT INTO userinfo (username, role, selected) VALUES ('user3', null, false);
INSERT INTO userinfo (username, role, selected) VALUES ('user4', null, false);
